experiment_name: 'EndoSAM'

# Model
model:
  class_num: 1 # 20 + 1
  model_customized: True
  model_type: 'default' # ['default' 'vit_h', 'vit_b', 'vit_l']
  model_name: 'sam_vit_h_4b8939.pth'
  encoder_size: 1024  

# Dataset
dataset:
    class_names: ['background', instrument-clapster']
    dataset_dir: '/home/iu/Desktop/EndoVis/all_data'
    img_format: 'jpg'
    ann_format: 'png'

# Losses
losses:
  ce:
    weight: 0.5
  mse:
    weight: 0.5
    

# Optimizer
opt_params:
  lr_default:  1e-4

# Runner
max_iter: 50
val_iter: 5
# Dataloader  
train_bs: 2 # 8
val_bs: 2 # 8
num_workers: 16
num_token: 8

# Logger
log_folder: '../experiment/log'
model_folder: '../experiment/model'
ckpt_folder: '../experiment/checkpoint'
plot_folder: '../experiment/plots'


