experiment_name: EndoSAM
model:
  class_num: 2
  sam_model_customized: true
  sam_model_type: default
  sam_model_dir: /home/iu/Desktop/EndoSAM/sam_ckpts/default.pth
  encoder_size: 1024
dataset:
  class_names:
  - background
  - instrument-clapster
  dataset_dir: /home/iu/Downloads/all_data
  img_format: jpg
  ann_format: png
losses:
  ce:
    weight: 0.5
  mse:
    weight: 0.5
opt_params:
  lr_default: 0.0001
max_iter: 1
val_iter: 5
train_bs: 2
val_bs: 2
test_bs: 1
num_workers: 20
num_token: 4
log_folder: /home/iu/Desktop/EndoSAM_experiment/log
model_folder: /home/iu/Desktop/EndoSAM_experiment/model
ckpt_folder: /home/iu/Desktop/EndoSAM_experiment/checkpoint
plot_folder: /home/iu/Desktop/EndoSAM_experiment/plots
test_folder: /home/iu/Desktop/EndoSAM_experiment/inference
