experiment_name: 'EndoSAM'

# Model
model:
  class_num: 2 # 20 + 1
  sam_model_customized: True
  sam_model_type: 'default' # ['default' 'vit_h', 'vit_b', 'vit_l']
  sam_model_dir: '/home/iu/Desktop/sam_vit_h_4b8939.pth'
  encoder_size: 1024  

# Dataset
dataset:
    class_names: ['background', 'instrument-clapster']
    dataset_dir: '/home/iu/Desktop/EndoVis/all_data'
    img_format: 'jpg'
    ann_format: 'png'

# Losses
losses:
  ce:
    weight: 0.5
  mse:
    weight: 0.5
    

# Optimizer
opt_params:
  lr_default:  1e-4

# Runner
max_iter: 1
val_iter: 5
# Dataloader  
train_bs: 2 # 8
val_bs: 2 # 8
test_bs: 1
num_workers: 20
num_token: 4

# Logger
log_folder: '/home/iu/Desktop/EndoSAM_experiment/log'
model_folder: '/home/iu/Desktop/EndoSAM_experiment/model'
ckpt_folder: '/home/iu/Desktop/EndoSAM_experiment/checkpoint'
plot_folder: '/home/iu/Desktop/EndoSAM_experiment/plots'
test_folder: '/home/iu/Desktop/EndoSAM_experiment/inference'


